Add HW1.2
pmokeev/HomeWork-SPBU pull request #6
Opened 2021-02-15 16:04 UTC by pmokeev

2021-02-15 16:06 UTC, pmokeev commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +            var stringMainArray = StringCounterArray(mainArray);
Тут конечно надо исправить с var на string[]

2021-02-15 16:06 UTC, pmokeev commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +            var stringSortedMainArray = StringCounterArray(sortedMainArray);
И тут тоже

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +            var lenArray = charArray.Length;
charArray.Length считается за константное время, так что сохранять его значение в отдельную переменную необязательно

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +        public static void PrintHello()
Взаимодействие с пользователем стоит делать только в Program, либо отдельно. Если мне BWT нужен только для LZW, зачем мне скачивать ещё и этот чудесный метод

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/TestsBWT.cs
> +        private static bool UncorrectTestCaseReverse()
Оно "Incorrect"

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/TestsBWT.cs
> +            return String.Compare(BWTransform.StraightBWT(startString), endString) == 0;
Строки в C# можно сравнивать оператором ==

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/TestsBWT.cs
> +        }
Тут тоже лучше через => записать

2021-02-15 16:38 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/TestsBWT.cs
> +        }
Тут тоже лучше через => записать

2021-02-15 16:48 UTC, yurii-litvinov requested changes
Это самая что ни на есть наивная реализация алгоритма, разве что таблица вращений заменена на таблицу суффиксов, которая тоже O(n^2) по памяти. С таким решением можно претендовать только на 3 балла (ну и на самом деле всё более-менее ок, так что готов поставить 2.5). Таблицы явно хранить совершенно ни к чему — например, сортировать можно не строки, а индексы начал суффиксов. Зная исходную строку и индекс, можно получить суффикс, явно его не храня.

2021-02-18 12:47 UTC, yurii-litvinov approved these changes
Итого, с алгоритмической точки зрения это вроде как то, что я хотел. С точки зрения C# видно, что Вы без идей, что происходит, но Вы пока и не должны иметь идеи, что происходит :) Так что зачтена, 5 баллов, отличная работа.

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +    public interface IComparable
В стандартной библиотеке такой есть :)

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +        public int nextRank;
Буквально с завтра public-поля будут строго-настрого запрещены, Вам повезло :)

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +    class Suffix : IComparable<Suffix>
И главное, что Вы пользуетесь не своим интерфейсом, а как раз библиотечным --- он генерик, в отличие от Вашего

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +            index = newIndex;
Есть ключевое слово this: `this.index = index;`, это позволит параметры конструктора называть по-человечески, и вместе с тем компилятор не запутается.

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +            Array.Sort(suffixesArray);
Только ради этого заморачивались с компаратором? Можно было просто воспользоваться первой домашкой :)

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +
Лишняя пустая строчка, перед `}` пустые строки не ставятся по стайлгайду

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +        private static int[] SuffixArray(string currentString)
Надо называть методы глаголами в повелительной форме, CreateSuffixArray, например

2021-02-18 12:47 UTC, yurii-litvinov commented on HW1/BWTAlgorithm/BWTAlgorithm/BWTransform.cs
> +        private static Tuple<string, int>[] StringCounterArray(char[] charArray)
Вообще, есть Tuple, а есть ValueTuple, и вторая тут была бы, наверное, более уместна. Но про это, опять-таки, завтра.

2021-02-19 06:32 UTC, merged